import type { ReportDocument } from './report-schema.js';

function list(items: readonly string[]): string { return items.length ? items.map((item) => `- ${item}`).join('\n') : '- 暂无'; }

export function renderReportMarkdown(report: ReportDocument, generatedAt = new Date()): string {
  return [
    `# ${report.coreInfo.projectName}｜AI 调研报告`,
    '',
    `> 生成时间：${generatedAt.toISOString()}`,
    '',
    '## 一、项目核心信息',
    '',
    `- 项目：${report.coreInfo.projectName}`,
    `- X 账号：${report.coreInfo.handle}`,
    `- 当前阶段：${report.coreInfo.stage}`,
    '',
    report.coreInfo.summary,
    '',
    '## 二、项目背景/背书账号',
    '',
    report.coreInfo.background || '当前无法确认知名 Crypto 背书账号或机构背景。',
    '',
    '## 三、当前进展',
    '',
    report.focusReason.currentProgress,
    '',
    '## 四、优点',
    '',
    list(report.focusReason.strengths),
    '',
    '## 五、缺点',
    '',
    list(report.focusReason.weaknesses),
    '',
    '## 六、关注理由',
    '',
    report.focusReason.reason,
    '',
    '## 七、标签',
    '',
    report.tags.map((tag) => '`' + tag + '`').join(' · '),
    '',
    '## 八、核心论点',
    '',
    list(report.thesis),
    '',
    '## 九、参与玩法',
    '',
    list(report.playbook),
    '',
    '## 十、L2 六赛道深挖',
    '',
    report.l2Tracks.map((track) => [`### ${track.title}｜${track.score.toFixed(1)} / 10`, '', track.summary, '', list(track.findings), '', track.evidence.length ? `证据：${track.evidence.map((item) => item.claim + (item.sourceUrl ? `（[来源](${item.sourceUrl})）` : '')).join('；')}` : '证据：暂无可核验来源'].join('\n')).join('\n\n'),
    '',
    '## 十一、独立复核轮：证伪检查',
    '',
    `- 复核状态：${report.independentReview.status}`,
    '',
    '### 待证伪假设',
    '',
    list(report.independentReview.hypotheses),
    '',
    '### 证伪检查项',
    '',
    list(report.independentReview.falsificationChecks),
    '',
    '### 反证与冲突信息',
    '',
    list(report.independentReview.counterEvidence),
    '',
    `### 复核结论\n\n${report.independentReview.conclusion}`,
    '',
    report.independentReview.evidence.length ? `复核证据：${report.independentReview.evidence.map((item) => item.claim + (item.sourceUrl ? `（[来源](${item.sourceUrl})）` : '')).join('；')}` : '复核证据：暂无可核验来源',
    '',
    '## 十二、评分总览',
    '',
    `- 总分：${report.score.overall.toFixed(1)} / 100`,
    `- 置信度：${(report.score.confidence * 100).toFixed(0)}%`,
    `- 判断：${report.score.verdict}`,
    '',
    report.score.dimensions.map((item) => `- ${item.key}：${item.score.toFixed(1)} / 10｜${item.rationale}`).join('\n'),
    '',
    '## 十三、风险与证据链',
    '',
    report.risksEvidence.length ? report.risksEvidence.map((item) => `### 风险：${item.risk}\n\n${item.evidence.length ? item.evidence.map((evidence) => `- ${evidence.claim}${evidence.sourceUrl ? `（[来源](${evidence.sourceUrl})）` : ''}`).join('\n') : '- 暂无已确认证据'}`).join('\n\n') : '暂无已确认风险。',
    ''
  ].join('\n');
}
